include:
  - board: nice_nano_v2
    shield: clog_left
  - board: nice_nano_v2
    shield: clog_right
  - board: seeeduino_xiao_ble
    shield: clog_v2_left
  - board: seeeduino_xiao_ble
    shield: clog_v2_right
  - board: seeeduino_xiao_ble
    shield: geta_left
  - board: seeeduino_xiao_ble
    shield: geta_right
  - board: seeeduino_xiao_ble
    shield: the_moon
  - board: nice_nano_v2
    shield: osprette
  - board: boardsource_blok
    shield: osprette
  - board: boardsource_blok
    shield: clog_left
  - board: boardsource_blok
    shield: clog_right
  - board: boardsource_blok
    shield: the_paintbrush_left
  - board: nice_nano_v2
    shield: settings_reset
  - board: seeeduino_xiao_ble
    shield: xiao_settings_reset
