include:
  - board: nice_nano//zmk
    shield: clog_left
  - board: nice_nano//zmk
    shield: clog_right
  - board: xiao_ble//zmk
    shield: clog_v2_left
  - board: xiao_ble//zmk
    shield: clog_v2_right
  - board: xiao_ble//zmk
    shield: geta_left
  - board: xiao_ble//zmk
    shield: geta_right
  - board: nice_nano//zmk
    shield: osprette
  - board: boardsource_blok//zmk
    shield: osprette
  - board: boardsource_blok//zmk
    shield: clog_left
  - board: boardsource_blok//zmk
    shield: clog_right
  - board: boardsource_blok//zmk
    shield: the_paintbrush_left
  - board: nice_nano//zmk
    shield: settings_reset
  - board: xiao_ble//zmk
    shield: xiao_settings_reset
